name: C CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Standard
            make_args: ""
          - name: Debug
            make_args: "ARGS='-p -c -e'"

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make

    - name: Run tests
      run: |
        chmod +x run_tests.sh
        make test ${{ matrix.make_args }}
